DOCKER_CONFIG_DOCKER_REPO="tiny"
DOCKER_CONFIG_DOCKER_TAG="1.0"

DOCKER_VAR_BASE_DISTRO="none"
DOCKER_VAR_BASE_IMAGE="ubuntu"
DOCKER_VAR_BASE_IMAGE_TAG="24.04"

DOCKER_VAR_MAINTAINER="breeze101792@gmail.com"
DOCKER_VAR_USER_NAME="ducky"
DOCKER_VAR_USER_PASS="123456"
