DOCKER_CONFIG_DOCKER_REPO="fpga"
DOCKER_CONFIG_DOCKER_TAG="1.0"

DOCKER_VAR_BASE_DISTRO="ubuntu"
DOCKER_VAR_BASE_IMAGE="ubuntu"
DOCKER_VAR_BASE_IMAGE_TAG="22.04"

DOCKER_VAR_MAINTAINER="breeze101792@gmail.com"
DOCKER_VAR_USER_NAME="docker"
DOCKER_VAR_USER_PASS="123456"
